#!/bin/bash

if [ -e $1 ]
then
  echo "Error: $1 already exists"
else
  mkdir "$1"
  cd "$1"
  a=`expr ${#1} - 2`
  echo "[$2](http://uva.onlinejudge.org/external/${1:0:$a}/$1.html)\n===" > "README.md"
  cp "../a$1/$1.cpp" "s$1.cpp"
  #cat "../template.cpp" > "s$1.cpp"
  echo "" > "i$1.dat"
  echo "" > "o$1.dat"
fi
