#!/bin/bash

if [ -e $1 ]
then
  echo "Error: $1 already exists"
else
  mkdir "$1"
  cd "$1"
  a=`expr ${#1} - 2`
  echo "[Question: $1 \"$2\"](http://uva.onlinejudge.org/external/${1:0:$a}/$1.html)
===" > "README.md"
  cat "../template.cpp" > "s$1.cpp"
  touch "i$1.dat"
  touch "o$1.dat"
fi
